// Run with --extensionTestsPath in an isolated VS Code instance (see TESTING).
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vscode = require('vscode');
exports.run = async function () {
  const extension = vscode.extensions.getExtension('an5orm.an5-orm-vscode');
  assert.ok(extension, 'Extension should be discovered');
  await extension.activate();
  assert.equal(extension.isActive, true);
  const commands = await vscode.commands.getCommands(true);
  for (const command of ['an5.connections.manage', 'an5.connections.add', 'an5.connections.refresh', 'an5.connections.test', 'an5.mcp.install']) assert.ok(commands.includes(command), command);
  await vscode.commands.executeCommand('workbench.view.extension.an5');
  await vscode.commands.executeCommand('an5.connections.manage');
  assert.ok(vscode.window.tabGroups.all.flatMap(g => g.tabs).some(t => t.label === 'AN5 · Connections'), 'Connection manager webview should open');
  const folder = vscode.workspace.workspaceFolders[0];
  await vscode.commands.executeCommand('an5.openConfig', folder);
  const schemaDir = path.join(folder.uri.fsPath, 'an5Schema');
  fs.mkdirSync(schemaDir, { recursive: true });
  const schemaFile = path.join(schemaDir, 'host.an5');
  fs.writeFileSync(schemaFile, 'model NativeHost {\n id INT @id\n}');
  await vscode.commands.executeCommand('an5.schema.openModel', { folder, model: { name: 'NativeHost' } });
  assert.equal(vscode.window.activeTextEditor.document.uri.fsPath, schemaFile);
  const config = path.join(folder.uri.fsPath, 'an5Orm.config.js');
  assert.ok(fs.existsSync(config));
  const text = fs.readFileSync(config, 'utf8');
  assert.match(text, /connectionString: process.env.DATABASE_URL/);
  assert.doesNotMatch(text, /generateComments/);
  assert.match(text, /golang:/);
  fs.writeFileSync(path.join(folder.uri.fsPath, '.env'), 'DATABASE_URL=sqlite::memory:');
  const child = path.join(folder.uri.fsPath, 'nested-project'); fs.mkdirSync(child, { recursive: true });
  fs.writeFileSync(path.join(child, 'an5Orm.config.js'), 'module.exports={connectionString:"sqlite::memory:"}');
  const { ConnectionUi } = require(path.join(extension.extensionPath, 'dist/connections/ui.js'));
  const reader = Object.create(ConnectionUi.prototype); reader.store = { list: () => ({ profiles: [] }) };
  const entries = reader.getChildren({ root: folder });
  assert.ok(entries.some(e => e.profile?.project), 'Project connection should appear without import');
  const childFolder = reader.projects().find(p => p.uri.fsPath === child); assert.ok(childFolder);
  assert.equal(reader.projectFor(vscode.Uri.file(path.join(child, 'file.ts'))).uri.fsPath, child);
  assert.ok(commands.includes('workbench.mcp.listServer'), 'MCP server list command should exist');
  console.log('AN5 Extension Host: activation, Activity Bar, webview, schema navigation, config and MCP commands passed.');
};
